forum/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from forum.views import ForumLV, ForumDV, ForumCreateView, ForumChangeLV, ForumDeleteView, ForumUpdateView

app_name = 'forum'

urlpatterns = [
    path('', ForumLV.as_view(), name="index"),
    re_path(r'^forum/(?P<slug>[-\w]+)/$', ForumDV.as_view(), name="forum_detail"),
    path('add/', ForumCreateView.as_view(), name="add"),
    path('change/', ForumChangeLV.as_view(), name="change"),
    path('<int:pk>/delete/', ForumDeleteView.as_view(), name="delete"),
    path('<int:pk>/update/', ForumUpdateView.as_view(), name="update"),
]

saferestaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, UserCreateView, UserCreateDoneView

urlpatterns = [
    path('', HomeView.as_view(), name="home"), # home 연결
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name="register"),
    path('accounts/register/done/', UserCreateDoneView.as_view(), name="register_done"),
    path('saferestaurantinfo/', include('saferestaurantinfo.urls')),
    path('forum/', include('forum.urls')),
]

forum/models.py
from django.db import models

from django.urls import reverse

from django.contrib.auth.models import User

from django.utils.text import slugify

# Create your models here.

class Forum(models.Model):

    title = models.CharField(verbose_name="TITLE", max_length=100)
    slug = models.SlugField(verbose_name="SLUG", max_length=100, allow_unicode=True, help_text="one word for title alias") # this is title -> this-is-title
    addr = models.CharField(verbose_name="ADDRESS", max_length=1000)
    addr_detail = models.CharField(verbose_name="ADDRESS DETAIL", max_length=200, blank=True)
    description = models.CharField(verbose_name="DESCRIPTION", max_length=2000)
    create_dt = models.DateTimeField(verbose_name="CREATE DATE", auto_now_add=True)
    modify_dt = models.DateTimeField(verbose_name="MODIFY DATE", auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="OWNER")

    class Meta:
        verbose_name = 'forum'
        verbose_name_plural = 'forums'
        db_table = 'forum'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("forum:forum_detail", args=(self.slug,)) # /blog/this-is-title

    def get_previous(self): # 이전 글 가져오기
        return self.get_previous_by_modify_dt()

    def get_next(self): # 다음 글 가져오기
        return self.get_next_by_modify_dt()

    # 상속 받은 메서드 재정의
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
    

forum/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic import CreateView, DeleteView, UpdateView
from forum.models import Forum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from saferestaurant.views import OwnerOnlyMixin

# Create your views here.

class ForumLV(ListView):
    # 목록을 조회해서 
    model = Forum # Post.objects.all()
    # 템플릿(default : blog/post_list.html)에 데이터(default: object_list) 전달
    template_name = "forum/forum_all.html"
    context_object_name = "forums"
    paginate_by = 3 # 페이징 처리 설정 (한 화면에 2개씩 표시)

class ForumDV(DetailView):
    model = Forum 

class ForumCreateView(LoginRequiredMixin, CreateView):
    model = Forum
    # fields = ['title', 'slug', 'description', 'content', 'tags']
    fields = ['title', 'slug', 'addr', 'addr_detail', 'description']
    initial = {'slug': 'auto-filling-do-not-input'} 
    #fields = ['title', 'description', 'content', 'tags'] 
    success_url = reverse_lazy('forum:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class ForumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'forum/forum_change_list.html'

    def get_queryset(self):
        return Forum.objects.filter(owner=self.request.user)

class ForumDeleteView(OwnerOnlyMixin, DeleteView) :
    model = Forum
    success_url = reverse_lazy('forum:index')

class ForumUpdateView(OwnerOnlyMixin, UpdateView):
    model = Forum
    # fields = ['title', 'slug', 'description', 'content', 'tags']
    fields = ['title', 'slug', 'addr','addr_detail','description']
    success_url = reverse_lazy('forum:index')

    

forum/templates/forum/forum_all.html
{% extends 'base.html' %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>사용자 제보 안심식당 게시판</h1>
    <hr>
    <br>
    <div>
        <button class="btn btn-info"><a href="{% url 'forum:add' %}" style="color:white">제보글 작성</a></button>
        <button class="btn btn-info"><a href="{% url 'forum:change' %}" style="color:white">정보 수정(작성자만 가능)</a></button>
    </div>
    {% for forum in forums %}
        <hr>
        <h3><a href="/forum/forum/{{ forum.slug }}/">{{ forum.title }}</a> [게시자 : {{ forum.owner }}]</h3>
        {# <h3><a href="{% forum.get_absolute_url %}">{{ forum.title }}</a></h3> #}
        {{ forum.modify_dt }}
        <p>{{ forum.addr }}</p>
        <p>{{ forum.description }}</p>
        <br><br>
    {% endfor %}
    <hr>

    {# page_obj : paging과 관련된 정보를 관리하는 객체 #}
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
    {% endif %}

    &nbsp;&nbsp;[ Page {{ page_obj.number }} of {{  page_obj.paginator.num_pages }} ]&nbsp;&nbsp;

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
    {% endif %}

{% endblock %}

forum/templates/forum/forum_archive.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Archives until {% now "N d, Y" %}</h1>

    {# date_list : ArchiveIndexView에서 제공하는 데이터 #}

    {% for date in date_list %}
    <a href="{% url 'forum:forum_year_archive' date|date:'Y' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        Year-{{ date|date:"Y" }}</a>
    {% endfor %}


    <br><br>

    <div>
        <ul>
            {% for forum in object_list %}
            <li class="h5">
                {{ forum.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ forum.get_absolute_url }}"><strong>{{ forum.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

forum/templates/forum/forum_archive_day.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Archives for {{ day|date:"N d, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for forum in object_list %}
            <li class="h5">
                {{ forum.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ forum.get_absolute_url }}"><strong>{{ forum.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

forum/templates/forum/forum_archive_month.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Archives for {{ month|date:"N, Y" }}</h1>
 
    {% for date in date_list %}
    <a href="{% url 'forum:forum_day_archive' date|date:'Y' date|date:'m' date|date:'d' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        {{ date|date:"d" }}</a>
    {% endfor %}

    <br><br>

    <div>
        <ul>
            {% for forum in object_list %}
            <li class="h5">
                {{ forum.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ forum.get_absolute_url }}"><strong>{{ forum.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

forum/templates/forum/forum_archive_year.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Archives for {{ year|date:"Y" }}</h1>

    {% for date in date_list %}
    <a href="{% url 'forum:forum_month_archive' date|date:'Y' date|date:'m' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        {{ date|date:"F" }}</a>
    {% endfor %}

    <br><br>

    <div>
        <ul>
            {% for forum in object_list %}
            <li class="h5">
                {{ forum.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ forum.get_absolute_url }}"><strong>{{ forum.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

forum/templates/forum/forum_change_list.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Change - {{user}}</h1>
    <br>

    <table class="table table-bordered table-sm table-striped">

        <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Address</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.addr }} {{ item.addr_detail }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'forum:update' item.id %}">Update</a></td>
            <td><a href="{% url 'forum:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

forum/templates/forum/forum_confirm_delete.html
{% extends "base.html" %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h1>Forum Delete</h1>
    <br>

    <form action="." method="forum">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

{% endblock %}

forum/templates/forum/forum_detail.html
{% extends 'base.html' %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}

    <h2 id='titles'>{{ object.title }}</h2>
    <p id = 'addr'>{{ object.addr }}</p>
    <div style="height:100px; background-color:gainsboro; padding: 10px;">
        {{object.description}}
    </div>
    <div style="border: 10px solid gainsboro;">
        <div id="map" style="height:400px; width:100%;border: 1px solid grey;"></div>
    </div>
    <p>
        {% if object.get_next %}
        <a href="{{ object.get_next.get_absolute_url }}">{{ object.get_next }}</a>
        {% endif %}
        &nbsp;|&nbsp;
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}">{{ object.get_previous }}</a>
        {% endif %}
    </p>

    <div>
        {{ object.modify_dt }}
    </div>
    

{% endblock %}


{% block custom_js %}
<script>
    var titles = document.getElementById('titles').innerText;
    var addr = document.getElementById('addr').innerText;
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };  

    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();

    // 주소로 좌표를 검색합니다
    geocoder.addressSearch(addr, function(result, status) {

        // 정상적으로 검색이 완료됐으면 
        if (status === kakao.maps.services.Status.OK) {
            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

            // 결과값으로 받은 위치를 마커로 표시합니다
            var marker = new kakao.maps.Marker({
                map: map,
                position: coords
            });

            // 인포윈도우로 장소에 대한 설명을 표시합니다
            var infowindow = new kakao.maps.InfoWindow({
                content: '<div style="width:150px;text-align:center;padding:6px 0; border: 1px solid gainsboro;">'+ titles + '</div>'
            });
            infowindow.open(map, marker);

            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
            map.setCenter(coords);
        } 
    });  
</script>

{% endblock custom_js %}

forum/templates/forum/forum_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
<title>saferestaurant-Forum</title>
{% endblock %}

{% block main_content %}
    <h1>Forum Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your post.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.slug|add_class:"form-control"|attr:"readonly" }}
            </div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>

        <div class="form-group row" >
            {{ form.addr|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.addr|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.addr.help_text }}</small>
        </div>
        <button id="addr-submit" class="btn btn-info" type="button" style="margin-top: 10px; width: 150px;margin: 0px 205px 20px;">주소 확인</button>
        <div style="border: 10px solid gainsboro;">
            <div id="map" style="height:400px; width:100%;border: 1px solid grey;"></div>
        </div>

        <div class="form-group row">
            {{ form.addr_detail|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.addr_detail|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.addr_detail.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.description.help_text }}</small>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
                <input type="hidden" name='next' value="{{ next }}"/>
            </div>
        </div>

    </form>

{% endblock main_content %}

{% block custom_js %}
<script>
$(function() {
    var newValue;
    // 모든 텍스트의 변경에 반응합니다.
    $("#addr-submit").on("click", function() {
    
        // 현재 변경된 데이터 셋팅
        var addr = $('#id_addr').val();
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };  

        // 지도를 생성합니다    
        var map = new kakao.maps.Map(mapContainer, mapOption); 

        // 주소-좌표 변환 객체를 생성합니다
        var geocoder = new kakao.maps.services.Geocoder();

        // 주소로 좌표를 검색합니다
        geocoder.addressSearch(addr, function(result, status) {
            // 정상적으로 검색이 완료됐으면 
            if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: '<div style="width:150px;text-align:center;padding:6px 0; border: 1px solid gainsboro;">주소 마커</div>'
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            } 
        });  
    });
});
</script>
{% endblock custom_js %}